<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Day01.fs"/>
        <Compile Include="Day02.fs"/>
        <Compile Include="Day03.fs"/>
        <Compile Include="Day04.fs"/>
        <Compile Include="Day05.fs"/>
        <Compile Include="Day06.fs"/>
        <Compile Include="Day07.fs"/>
        <Compile Include="Library.fs"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Common\Common.fsproj"/>
    </ItemGroup>

</Project>
